services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot_psychologue:v1
    container_name: bot_psychologue
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_FILE=
    restart: unless-stopped
